// banks.js

const banks = [
    {
        key: 'creditkasa',
        title: 'CreditKasa',
        website: 'creditkasa.com.ua',
        image: './images/banks/creditkasa.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 300,
        percent: 0.01,
        rating: 98.8,
        sum: 20000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/2710?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'selfiecredit',
        title: 'SelfieCredit',
        website: 'selfiecredit.com.ua',
        website: 'selfiecredit.com.ua',
        image: './images/banks/selfiecredit.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 365,
        percent: 0.01,
        rating: 98.7,
        sum: 25000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/2816?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'miloan',
        title: 'MILOAN',
        website: 'miloan.ua',
        image: './images/banks/miloan.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 120,
        percent: 0.01,
        rating: 99.1,
        sum: 23000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/1436?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'egroshi',
        title: 'EGROSHI',
        website: 'egroshi.com',
        image: './images/banks/egroshi.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 14,
        percent: 0.01,
        rating: 99.2,
        sum: 20000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/1711?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'slon',
        title: 'Slon Credit',
        website: 'sloncredit.ua',
        image: './images/banks/slon.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 365,
        percent: 0.01,
        rating: 99.1,
        sum: 25000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/1921?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'sgroshi',
        title: 'ШвидкоГроші',
        website: 'sgroshi.com.ua',
        image: './images/banks/sgroshi.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 140,
        percent: 0.01,
        rating: 99.0,
        sum: 30000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/2793?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'tengo',
        title: 'Tengo',
        website: 'tengo.ua',
        image: './images/banks/tengo.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 120,
        percent: 0.01,
        rating: 98.7,
        sum: 23000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/2728?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'pango',
        title: 'Pango',
        website: 'pango.com.ua',
        image: './images/banks/pango.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 120,
        percent: 0.01,
        rating: 94.4,
        sum: 12000,
        advUrl: 'https://rdr.salesdoubler.com.ua/in/offer/6373?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'avans',
        title: 'AvansCredit',
        website: 'avans.credit',
        image: './images/banks/avans.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 120,
        percent: 0.01,
        rating: 98.9,
        sum: 20000,
        advUrl: 'https://go.salesdoubler.net/in/offer/3365?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'credit7',
        title: 'Credit7',
        website: 'credit7.ua',
        image: './images/banks/credit7.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 365,
        percent: 0.01,
        rating: 98.9,
        sum: 30000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/2099?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'finsfera',
        title: 'Finsfera',
        website: 'finsfera.ua',
        image: './images/banks/finsfera.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 360,
        percent: 0.01,
        rating: 98.3,
        sum: 14000,
        advUrl: 'https://go.salesdoubler.net/in/offer/3309?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'creditplus',
        title: 'CreditPlus',
        website: 'creditplus.ua',
        image: './images/banks/creditplus.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 365,
        percent: 0.01,
        rating: 99.2,
        sum: 15000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/1844?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'mycredit',
        title: 'MyCredit',
        website: 'mycredit.ua',
        image: './images/banks/mycredit.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 30,
        percent: 0.01,
        rating: 99.1,
        sum: 12000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/2681?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'money4you',
        title: 'Money4You',
        website: 'money4you.ua',
        image: './images/banks/money4you.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 80,
        percent: 0.01,
        rating: 99.0,
        sum: 15000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/2217?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'starfin',
        title: 'Starfin',
        website: 'starfin.com.ua',
        image: './images/banks/starfin.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 120,
        percent: 0.01,
        rating: 98.8,
        sum: 20000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/5706?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'finbar',
        title: 'Finbar',
        website: 'finbar.com.ua',
        image: './images/banks/finbar.jpg',
        ageFrom: 18,
        ageTo: 70,
        term: 120,
        percent: 0.01,
        rating: 97.6,
        sum: 20000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/3485?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'moneyveo',
        title: 'MoneyVeo',
        website: 'moneyveo.ua',
        image: './images/banks/moneyveo.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 30,
        percent: 0.01,
        rating: 98.9,
        sum: 27000,
        advUrl: 'https://rdr.salesdoubler.com.ua/in/offer/8084?hash=Fh96aU&aid=63223&transaction_id=3k80vps&tid1=Telegram'
    },
    // {
    //     key: 'soscredit',
    //     title: 'SosCredit',
    //     website: 'soscredit.ua',
    //     image: './images/banks/soscredit.jpg',
    //     ageFrom: 18,
    //     ageTo: 65,
    //     term: 65,
    //     percent: 0.01,
    //     rating: 99.1,
    //     sum: 20000,
    //     advUrl: 'https://rdr.fmcgsd.net/in/offer/2788?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    // },
    {
        key: 'tvoyapozika',
        title: 'ТвояПозика',
        website: 'tpozyka.com',
        image: './images/banks/tvoyapozika.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 169,
        percent: 1.1,
        rating: 98.0,
        sum: 150000,
        advUrl: 'https://rdr.fmcgsd.net/in/offer/2641?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    {
        key: 'firstcredit',
        title: 'FirstCredit',
        website: 'firstcredit.com.ua',
        image: './images/banks/firstcredit.jpg',
        ageFrom: 18,
        ageTo: 65,
        term: 30,
        percent: 0.01,
        rating: 95.0,
        sum: 10000,
        advUrl: 'https://rdr.salesdoubler.com.ua/in/offer/6365?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    },
    // {
    //     key: 'trebacredit',
    //     title: 'TrebaCredit',
    //     website: 'treba.credit',
    //     image: './images/banks/trebacredit.jpg',
    //     ageFrom: 18,
    //     ageTo: 65,
    //     term: 30,
    //     percent: 0.15,
    //     rating: 97.2,
    //     sum: 10000,
    //     advUrl: 'https://rdr.fmcgsd.net/in/offer/6345?hash=Fh96aU&aid=63223&transaction_id=3k80vp&tid1=Telegram'
    // }
];

module.exports = banks;
